title: "Pollus: Polling For Today"
description: Polls and Surveys NOW!
sitename: Pollus
baseurl: ''
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME